### ISSUE TITLE
Upgrade core dependencies

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#855]
I'm creating this issue to keep discussing the upgrade of some core dependencies of this plugin, originated in #852 (@lesha1201).

### typescript-eslint
We could support both v5 and v6, actually. I think it will make things more complicated, so let me think about it. There are other things more critical to be updated now.

### Prettier
I already tried to upgrade to v3, but had to revert it because of breaking changes introduced. [You can find more details in the revert PR](https://github.com/testing-library/eslint-plugin-testing-library/pull/826).

### TypeScript
Definitely interested in upgrading this one, and it's actually needed to upgrade prettier to v3 as described in the previous revert PR.

### Jest
Not sure why this was updated in #852, but we need to upgrade it anyway. ~Shouldn't be blocked by anything~ This is blocked by Node.js v12 which is not supported by Jest v29.

So our priorities should be:

- [X] Upgrade TS to v5 --> #858
- [x] Upgrade Prettier to v3 --> #932
- [x] Upgrade typescript-eslint to v7 (breaking change)
- [x] Update Node.js engine requirement to `^18.18.0 || >=20.0.0` (breaking change) --> #898 

### Other improvements
When Node.js compatibility for non-supported versions is dropped, we can apply more improvements:

- [x] ~Upgrade Jest to v29~ Migrate test runner to vitest --> #1102
- [x] Upgrade TypeScript to the last v5.X (enabling pending things from #858) --> #1132
- [x] Replace npm with pnpm as the package manager --> #966
- [x] Use tsup for bundling in both CJS and ESM formats --> #900

**Comment by Belco90** [comment]
Just thinking out loud: another migration update plan for this plugin could be releasing a new major that upgrades typescript-eslint to v6 + drops Node.js support for the same versions as the future ESLint v9. Then when ESLint v9 gets released we don't release another major but a minor supporting both ESLint v8 and v9.

**Comment by lesha1201** [comment]
@Belco90 Do you want to upgrade TS or I can open PR? I saw your notes about updating `tsconfig` in this PR https://github.com/testing-library/eslint-plugin-testing-library/pull/826 but not sure what exactly you want to update. I can open PR with these changes - https://github.com/testing-library/eslint-plugin-testing-library/pull/852/commits/20c87e82f8d66d6a22a38773379d66676a8edadd and you can either ask me to add some changes to `tsconfig` or push them directly.

**Comment by Belco90** [comment]
> @Belco90 Do you want to upgrade TS or I can open PR? I saw your notes about updating `tsconfig` in this PR #826 but not sure what exactly you want to update. I can open PR with these changes - [20c87e8](https://github.com/testing-library/eslint-plugin-testing-library/commit/20c87e82f8d66d6a22a38773379d66676a8edadd) and you can either ask me to add some changes to `tsconfig` or push them directly.

Feel free to create a PR! I can ask for some changes to `tsconfig` if needed.

**Comment by Belco90** [comment]
I've updated the description, so we release a v7 dropping support for older Node.js versions similar to [typescript-eslint v7](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7#breaking-changes).

**Comment by Belco90** [comment]
[ESLint v9 has been released](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/), so all the planned changes here can be done under the new major of the plugin.

**Comment by G-Rath** [comment]
fwiw I've opened #932 upgrading Prettier to v3

**Comment by G-Rath** [comment]
fwiw, over in `eslint-plugin-jest` we've have [multiple major versions of `@typescript-eslint/utils` as a direct dependency](https://github.com/jest-community/eslint-plugin-jest/blob/main/package.json#L61) for a while now without issue - there's a few edge cases with package managers sometimes aiming for the latest major and erroring if it's not compatible with the rest of the tree which is not ideal but at least devs can have everything happy if they're using slightly older majors with only a bit of manual nudging
