### ISSUE TITLE
Release v3

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#93]
Recent update on dom-testing-library to v7 has originated few improvements for some existing rules and ideas for some new others. I'll wrap all those changes under release of plugin v3 for several reasons:

- One of them implies a breaking change so I think it's better to put everything under same major version rather than be releasing different minors and one major at some point.
- Most of them are related to new `waitFor` async util so I'd like to test all changes together before releasing them to check they make sense as a whole.
- Changes are closed to be finished so this won't take too long.

Changes under v3 will be:

- [x] **BREAKING CHANGE**: drop node v8 support #96 
- [x] **BREAKING CHANGE**: replace rule `no-get-by-for-checking-element-not-present` with `prefer-presence-queries` #90 
- [x] Feature: update rule `await-async-utils` with new `waitFor` async util #89 
- [x] Feature: new rule `prefer-wait-for` #88
- [x] Feature: new rule `no-wait-for-empty-callback` #92 
- [x] Feature: new rule `prefer-screen-queries` #95 (_optional, only if it ready when releasing v3. Otherwise it will go on v3.1_)

All PRs for mentioned changes will point to branch `v3` where everything will be tested together before releasing everything. I'll test this myself in a huge codebase with more than 3k tests, but I'd like to get other people running this on their projects too.

Thoughts?

**Comment by timdeschryver** [comment]
Let me know if/how I can help!

**Comment by Belco90** [comment]
@timdeschryver thanks!

- Issue 1) should be really easy to implement, I have that one under control.
- Issue 2) is merged
- I'm still trying to find out best way to put all your code together for issue 3). It works but tests are not passing because of the same reason as previous fixers. I got couple of ideas, if none work I'll pin you.
- For issue 4) I only have the idea, but didn't have time to check it. You could give it a try if you want!

**Comment by Belco90** [comment]
I think I'll add to this release dropping support for node v8. I'll update pipeline for making sure it accepts same versions as ESLint does.

**Comment by timdeschryver** [comment]
@Belco90 what about a rule about the usage of `screen`? 

```
// bad
component.someQuery()

// good
screen.someQuery()
````

No idea how tho, perhaps add all queries and verify that the `callee` of these queries is `screen`?

**Comment by Belco90** [comment]
That seems interesting. Could be something like `prefer-screen-queries`. Can you create an issue so we discuss further details there?
